apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: coolstore-cicd:tekton.dev/Task:coolstore-cicd/newman
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tekton.dev/v1","kind":"Task","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"coolstore-cicd:tekton.dev/Task:coolstore-cicd/newman"},"name":"newman","namespace":"coolstore-cicd"},"spec":{"params":[{"description":"The collection to run, typically a remote URL pointing to the collection","name":"COLLECTION","type":"string"},{"default":"newman-env.json","description":"The environment file to use from the newman-env configmap","name":"ENVIRONMENT"}],"steps":[{"args":["run","$(inputs.params.COLLECTION)","-e","/$(workspaces.newman-env.path)/$(inputs.params.ENVIRONMENT)","--bail"],"command":["newman"],"image":"quay.io/coolstore-demo/newman:latest","name":"collections-test"}],"workspaces":[{"description":"The newman environments to use for variables","name":"newman-env"}]}}
  creationTimestamp: "2024-12-16T07:28:47Z"
  generation: 1
  name: newman
  namespace: coolstore-cicd
  resourceVersion: "62191"
  uid: 4391b617-d9e2-4591-b6f3-8df61b97d7dc
spec:
  params:
  - description: The collection to run, typically a remote URL pointing to the collection
    name: COLLECTION
    type: string
  - default: newman-env.json
    description: The environment file to use from the newman-env configmap
    name: ENVIRONMENT
    type: string
  steps:
  - args:
    - run
    - $(inputs.params.COLLECTION)
    - -e
    - /$(workspaces.newman-env.path)/$(inputs.params.ENVIRONMENT)
    - --bail
    command:
    - newman
    computeResources: {}
    image: quay.io/coolstore-demo/newman:latest
    name: collections-test
  workspaces:
  - description: The newman environments to use for variables
    name: newman-env
