apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: coolstore-cicd:tekton.dev/Task:coolstore-cicd/npm
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tekton.dev/v1","kind":"Task","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"coolstore-cicd:tekton.dev/Task:coolstore-cicd/npm"},"name":"npm","namespace":"coolstore-cicd"},"spec":{"steps":[{"args":["npm install --package-lock"],"command":["/bin/sh","-c"],"image":"registry.redhat.io/ubi8/nodejs-14:latest","name":"npm-install","workingDir":"$(workspaces.source.path)"},{"args":["mkdir -p $(workspaces.source.path)/git-sha\ngit rev-parse --short HEAD | tee $(workspaces.source.path)/git-sha/commit-id"],"command":["/bin/bash","-c"],"image":"docker.io/maven:3.6.3-jdk-8","name":"save-commit-sha","workingDir":"$(workspaces.source.path)"}],"workspaces":[{"name":"source"}]}}
  creationTimestamp: "2024-12-16T07:28:47Z"
  generation: 1
  name: npm
  namespace: coolstore-cicd
  resourceVersion: "62196"
  uid: 972f5bb8-4891-4b94-9fa5-575a7c5df95c
spec:
  steps:
  - args:
    - npm install --package-lock
    command:
    - /bin/sh
    - -c
    computeResources: {}
    image: registry.redhat.io/ubi8/nodejs-14:latest
    name: npm-install
    workingDir: $(workspaces.source.path)
  - args:
    - |-
      mkdir -p $(workspaces.source.path)/git-sha
      git rev-parse --short HEAD | tee $(workspaces.source.path)/git-sha/commit-id
    command:
    - /bin/bash
    - -c
    computeResources: {}
    image: docker.io/maven:3.6.3-jdk-8
    name: save-commit-sha
    workingDir: $(workspaces.source.path)
  workspaces:
  - name: source
