apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: coolstore-cicd:tekton.dev/Task:coolstore-cicd/rox-image-scan
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tekton.dev/v1","kind":"Task","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"coolstore-cicd:tekton.dev/Task:coolstore-cicd/rox-image-scan"},"name":"rox-image-scan","namespace":"coolstore-cicd"},"spec":{"params":[{"description":"Full name of image to scan (example -- gcr.io/rox/sample:5.0-rc1)","name":"image","type":"string"},{"default":"json","description":"Output format (json | csv | table )","name":"output_format","type":"string"}],"steps":[{"image":"registry.redhat.io/advanced-cluster-security/rhacs-roxctl-rhel8:3.70","name":"rox-image-scan","script":"#!/usr/bin/env bash\nset +x\n\nif [ $(workspaces.acs-central.bound) == \"false\" ] ; then\n  echo \"No acs-central workspace was bound to task\"\n  exit 0\nfi\n\nexport ROX_CENTRAL_ENDPOINT=$(cat $(workspaces.acs-central.path)/rox_central_endpoint)\nexport ROX_API_TOKEN=$(cat $(workspaces.acs-central.path)/rox_api_token)\n\necho \"Scanning against endpoint ${ROX_CENTRAL_ENDPOINT}\"\n\nexport NO_COLOR=\"True\"\n\necho \"Scanning image: $(params.image)\"\n\nroxctl image scan --insecure-skip-tls-verify -e $ROX_CENTRAL_ENDPOINT --image $(params.image) --output $(params.output_format)"}],"workspaces":[{"description":"The secret with the central endpoint (rox-central_endpoint) and api token (rox_api_token)","name":"acs-central","optional":true}]}}
  creationTimestamp: "2024-12-16T07:28:47Z"
  generation: 1
  name: rox-image-scan
  namespace: coolstore-cicd
  resourceVersion: "62220"
  uid: 5c7b0e25-d0bd-465d-9812-9e1b9344bd44
spec:
  params:
  - description: Full name of image to scan (example -- gcr.io/rox/sample:5.0-rc1)
    name: image
    type: string
  - default: json
    description: Output format (json | csv | table )
    name: output_format
    type: string
  steps:
  - computeResources: {}
    image: registry.redhat.io/advanced-cluster-security/rhacs-roxctl-rhel8:3.70
    name: rox-image-scan
    script: |-
      #!/usr/bin/env bash
      set +x

      if [ $(workspaces.acs-central.bound) == "false" ] ; then
        echo "No acs-central workspace was bound to task"
        exit 0
      fi

      export ROX_CENTRAL_ENDPOINT=$(cat $(workspaces.acs-central.path)/rox_central_endpoint)
      export ROX_API_TOKEN=$(cat $(workspaces.acs-central.path)/rox_api_token)

      echo "Scanning against endpoint ${ROX_CENTRAL_ENDPOINT}"

      export NO_COLOR="True"

      echo "Scanning image: $(params.image)"

      roxctl image scan --insecure-skip-tls-verify -e $ROX_CENTRAL_ENDPOINT --image $(params.image) --output $(params.output_format)
  workspaces:
  - description: The secret with the central endpoint (rox-central_endpoint) and api
      token (rox_api_token)
    name: acs-central
    optional: true
