apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: coolstore-cicd:tekton.dev/Task:coolstore-cicd/task-create-pr
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tekton.dev/v1","kind":"Task","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"coolstore-cicd:tekton.dev/Task:coolstore-cicd/task-create-pr"},"name":"task-create-pr","namespace":"coolstore-cicd"},"spec":{"params":[{"description":"PR Title","name":"title","type":"string"},{"default":"","description":"The body of the PR request","name":"body","type":"string"},{"name":"branch","type":"string"},{"name":"gitea_server","type":"string"},{"name":"repo","type":"string"},{"name":"repo_owner","type":"string"},{"default":"gitea","description":"The name of the secret that has your gitea username and token","name":"git_secret","type":"string"}],"steps":[{"env":[{"name":"PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"$(params.git_secret)"}}},{"name":"USERNAME","valueFrom":{"secretKeyRef":{"key":"username","name":"$(params.git_secret)"}}},{"name":"EMAIL","valueFrom":{"secretKeyRef":{"key":"email","name":"$(params.git_secret)"}}}],"image":"registry.access.redhat.com/ubi8-minimal:8.8","name":"run-commands","script":"#!/usr/bin/env bash\n\nauth=$(echo -n \"$USERNAME:$PASSWORD\" | base64 -w 0)\n\ncurl --location 'https://$(params.gitea_server)/api/v1/repos/$(params.repo_owner)/$(params.repo)/pulls' \\\n--header 'Content-Type: application/json' \\\n--header \"Authorization: Basic $auth\" \\\n--data '{\n  \"assignee\": \"user1\",\n  \"base\": \"main\",\n  \"body\": \"$(params.body)\",\n  \"head\": \"$(params.branch)\",\n  \"title\": \"$(params.title)\"\n}'\n","workingDir":"$(workspaces.source.path)/git-update-digest-workdir"}],"workspaces":[{"name":"source"}]}}
  creationTimestamp: "2024-12-16T07:28:47Z"
  generation: 1
  name: task-create-pr
  namespace: coolstore-cicd
  resourceVersion: "62219"
  uid: cbeff1c7-f589-4d4c-974d-db9a685fed1b
spec:
  params:
  - description: PR Title
    name: title
    type: string
  - default: ""
    description: The body of the PR request
    name: body
    type: string
  - name: branch
    type: string
  - name: gitea_server
    type: string
  - name: repo
    type: string
  - name: repo_owner
    type: string
  - default: gitea
    description: The name of the secret that has your gitea username and token
    name: git_secret
    type: string
  steps:
  - computeResources: {}
    env:
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: $(params.git_secret)
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          key: username
          name: $(params.git_secret)
    - name: EMAIL
      valueFrom:
        secretKeyRef:
          key: email
          name: $(params.git_secret)
    image: registry.access.redhat.com/ubi8-minimal:8.8
    name: run-commands
    script: |
      #!/usr/bin/env bash

      auth=$(echo -n "$USERNAME:$PASSWORD" | base64 -w 0)

      curl --location 'https://$(params.gitea_server)/api/v1/repos/$(params.repo_owner)/$(params.repo)/pulls' \
      --header 'Content-Type: application/json' \
      --header "Authorization: Basic $auth" \
      --data '{
        "assignee": "user1",
        "base": "main",
        "body": "$(params.body)",
        "head": "$(params.branch)",
        "title": "$(params.title)"
      }'
    workingDir: $(workspaces.source.path)/git-update-digest-workdir
  workspaces:
  - name: source
