apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    operator.tekton.dev/last-applied-hash: a7dc28818aaca258f68b74887b0d5b6d21d323b15b4109bce810ee5c1ed90622
    tekton.dev/categories: Deployment
    tekton.dev/displayName: kn apply
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/platforms: linux/amd64,linux/s390x,linux/ppc64le,linux/arm64
    tekton.dev/tags: cli
  creationTimestamp: "2024-12-13T05:08:22Z"
  generation: 1
  labels:
    app.kubernetes.io/version: "0.2"
    operator.tekton.dev/operand-name: openshift-pipelines-addons
    operator.tekton.dev/provider-type: redhat
  name: kn-apply-1-11-0
  ownerReferences:
  - apiVersion: operator.tekton.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: TektonInstallerSet
    name: addon-versioned-Tasks-1.11-94wk8
    uid: eb9843ed-d1b7-40ec-b40e-9bc97008c20b
  resourceVersion: "53909"
  uid: 1f5d404d-69f6-4432-ba2c-1c96549222fc
spec:
  description: |-
    This task deploys a given image to a Knative Service.
    It uses `kn service apply` to create or update given knative service.
  params:
  - default: registry.redhat.io/openshift-serverless-1/client-kn-rhel8@sha256:bf6cf2e87fb19f7aa9a490b83c16af69834c0721220a643710a1b077959e91ca
    description: kn CLI container image to run this task
    name: KN_IMAGE
    type: string
  - description: Knative service name
    name: SERVICE
    type: string
  - description: Image to deploy
    name: IMAGE
    type: string
  steps:
  - args:
    - service
    - apply
    - $(params.SERVICE)
    - --image
    - $(params.IMAGE)
    command:
    - /ko-app/kn
    env:
    - name: HOME
      value: /tekton/home
    image: $(params.KN_IMAGE)
    name: kn
    resources: {}
    securityContext:
      runAsNonRoot: true
      runAsUser: 65532
