apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    operator.tekton.dev/last-applied-hash: a1e15524fefb5c6b1c1af497ee66a3b01d3e82197578a7433c6d6cc22d87616b
    tekton.dev/categories: CLI
    tekton.dev/displayName: kn
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/platforms: linux/amd64,linux/s390x,linux/ppc64le,linux/arm64
    tekton.dev/tags: cli
  creationTimestamp: "2024-12-13T05:08:22Z"
  generation: 1
  labels:
    app.kubernetes.io/version: "0.2"
    operator.tekton.dev/operand-name: openshift-pipelines-addons
    operator.tekton.dev/provider-type: redhat
  name: kn
  ownerReferences:
  - apiVersion: operator.tekton.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: TektonInstallerSet
    name: addon-custom-Task-952sd
    uid: 55450e27-c314-4d37-8ccc-20e8fef3986a
  resourceVersion: "53894"
  uid: cfdeb113-1cf5-462e-86f9-13610603f678
spec:
  description: This Task performs operations on Knative resources (services, revisions,
    routes) using kn CLI
  params:
  - default: registry.redhat.io/openshift-serverless-1/client-kn-rhel8@sha256:bf6cf2e87fb19f7aa9a490b83c16af69834c0721220a643710a1b077959e91ca
    description: kn CLI container image to run this task
    name: kn-image
    type: string
  - default:
    - help
    description: kn CLI arguments to run
    name: ARGS
    type: array
  steps:
  - args:
    - $(params.ARGS)
    command:
    - /ko-app/kn
    env:
    - name: HOME
      value: /tekton/home
    image: $(params.kn-image)
    name: kn
    resources: {}
    securityContext:
      runAsNonRoot: true
      runAsUser: 65532
