apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    operator.tekton.dev/last-applied-hash: 8ce38487778543438965694225e34408c78c03dfc703671aad7361b5f31bb2fc
    tekton.dev/displayName: openshift client
    tekton.dev/pipelines.minVersion: 0.17.0
    tekton.dev/tags: cli
  creationTimestamp: "2024-12-13T05:08:22Z"
  generation: 1
  labels:
    app.kubernetes.io/version: "0.2"
    operator.tekton.dev/operand-name: openshift-pipelines-addons
    operator.tekton.dev/provider-type: redhat
  name: openshift-client
  ownerReferences:
  - apiVersion: operator.tekton.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: TektonInstallerSet
    name: addon-custom-Task-952sd
    uid: 55450e27-c314-4d37-8ccc-20e8fef3986a
  resourceVersion: "53918"
  uid: 031a8495-3c3d-4190-9fc7-775fc7294c92
spec:
  description: |-
    This task runs commands against the cluster provided by user and if not provided then where the Task is being executed.
    OpenShift is a Kubernetes distribution from Red Hat which provides oc, the OpenShift CLI that complements kubectl for simplifying deployment and configuration applications on OpenShift.
  params:
  - default: oc help
    description: The OpenShift CLI arguments to run
    name: SCRIPT
    type: string
  - default: latest
    description: The OpenShift Version to use
    name: VERSION
    type: string
  steps:
  - env:
    - name: HOME
      value: /tekton/home
    image: image-registry.openshift-image-registry.svc:5000/openshift/cli:$(params.VERSION)
    name: oc
    resources: {}
    script: |
      #!/usr/bin/env bash

      [[ "$(workspaces.manifest-dir.bound)" == "true" ]] && \
      cd $(workspaces.manifest-dir.path)

      [[ "$(workspaces.kubeconfig-dir.bound)" == "true" ]] && \
      [[ -f $(workspaces.kubeconfig-dir.path)/kubeconfig ]] && \
      export KUBECONFIG=$(workspaces.kubeconfig-dir.path)/kubeconfig

      $(params.SCRIPT)
    securityContext:
      runAsNonRoot: true
      runAsUser: 65532
  workspaces:
  - description: The workspace which contains kubernetes manifests which we want to
      apply on the cluster.
    name: manifest-dir
    optional: true
  - description: The workspace which contains the the kubeconfig file if in case we
      want to run the oc command on another cluster.
    name: kubeconfig-dir
    optional: true
