apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    operator.tekton.dev/last-applied-hash: 69f40a4e8801d78bf689c4ddb6134c739fd7970054e2fdcbc1ee6dfbd6bd5b03
    tekton.dev/categories: Git
    tekton.dev/displayName: pull request
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/platforms: linux/amd64,linux/s390x,linux/ppc64le
    tekton.dev/tags: SCM
  creationTimestamp: "2024-12-13T05:08:23Z"
  generation: 1
  labels:
    app.kubernetes.io/version: "0.1"
    operator.tekton.dev/provider-type: community
  name: pull-request
  ownerReferences:
  - apiVersion: operator.tekton.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: TektonInstallerSet
    name: addon-custom-communityTask-2qtsc
    uid: e8c93a3d-1ba2-4fe2-92c9-fd57bdbd5c85
  resourceVersion: "53965"
  uid: 6d16948c-da5a-40a3-9ec8-1b338fd3a1fd
spec:
  description: |-
    This Task allows a user to interact with an SCM (source control management) system through an abstracted interface
    This Task works with both public SCM instances and self-hosted/enterprise GitHub/GitLab instances. In download mode, this Task will look at the state of an existing pull request and populate the pr workspace with the state of the pull request, including the .MANIFEST file. In upload mode, this Task will look at the contents of the pr workspace and compare it to the .MANIFEST file (if it exists).
  params:
  - description: If "download", the state of the pull request at `url` will be fetched.
      If "upload" then the pull request at `url` will be updated.
    name: mode
    type: string
  - description: The URL of the Pull Reuqest, e.g. `https://github.com/bobcatfish/catservice/pull/16`
    name: url
    type: string
  - description: The type of SCM system, currently `github` or `gitlab`
    name: provider
    type: string
  - description: The name of an opaque secret containing a key called "token" with
      a base64 encoded SCM token
    name: secret-key-ref
    type: string
  - default: "false"
    description: If "true", certificate validation will be disabled
    name: insecure-skip-tls-verify
    type: string
  steps:
  - args:
    - -url
    - $(params.url)
    - -path
    - $(workspaces.pr.path)
    - -mode
    - $(params.mode)
    - -provider
    - $(params.provider)
    - -insecure-skip-tls-verify
    - $(params.insecure-skip-tls-verify)
    command:
    - /ko-app/pullrequest-init
    env:
    - name: AUTH_TOKEN
      valueFrom:
        secretKeyRef:
          key: token
          name: $(params.secret-key-ref)
    image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/pullrequest-init@sha256:69633ecd0e948f6462c61bb9e008b940a05b143ef51c67e6e4093278a23dac53
    name: pullrequest-init
    resources: {}
  workspaces:
  - name: pr
