apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name:  quarkus-hello-cicdrun
  namespace: tassinari
spec:
  pipelineRef:
    name:  quarkus-hello-cicd
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: pvc-workspace
    - name: maven-settings
      configMap:
        name: maven-settings