apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-quarkus-pipeline
  namespace: tassinari
spec:
  params:
    - default: 'https://github.com/fctassinari/quarkus-hello.git'
      name: APP_SOURCE_GIT
      type: string
    - default: main
      name: APP_SOURCE_REVISION
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.APP_SOURCE_GIT)
        - name: revision
          value: $(params.APP_SOURCE_REVISION)
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '0'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: hello-quarkus
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:868966ef9d4b54952d8a74eb83bba40eb1f52c0148994fa704efd0e3797c61c5
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: unit-tests
      params:
        - name: GOALS
          value:
            - package
            - '-f'
            - hello-quarkus
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: source
          workspace: workspace
        - name: maven-settings
          workspace: maven-settings
    - name: code-analysis
      params:
        - name: GOALS
          value:
            - install
            - 'sonar:sonar'
            - '-f'
            - hello-quarkus
            - >-
              -Dsonar.host.url=https://sonarqube-cicd.apps.cluster-ntsm8.sandbox564.opentlc.com
            - '-Dsonar.userHome=/tmp/sonar'
            - '-Dsonar.login=squ_2946bd84ac48b6460a90ba4879c3598d1694a2d0'
            - '-DskipTests=true'
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: source
          workspace: workspace
        - name: maven-settings
          workspace: maven-settings
    - name: dependency-report
      taskRef:
        name: dependency-report
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: workspace
        - name: maven-settings
          workspace: maven-settings
      params:
        - name: SOURCE_DIR
          value: hello-quarkus
  workspaces:
    - name: maven-settings
    - name: workspace
