apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: quarkus-hello-pipeline
  namespace: tassinari
spec:
  params:
    - default: 'https://github.com/fctassinari/quarkus-hello.git'
      name: APP_SOURCE_GIT
      type: string
    - default: main
      name: APP_SOURCE_REVISION
      type: string
    - name: APP_IMAGE_TAG
      type: string
      default: latest
      description: The application image tag to build
    - name: APP_MANIFESTS_GIT
      type: string
      description: The application manifests git repository
      default: 'https://github.com/fctassinari/quarkus-hello-config.git'
#      default: http://{{ r_gogs_route.resources[0].spec.host }}/gogs/spring-petclinic-config
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.APP_SOURCE_GIT)
        - name: revision
          value: $(params.APP_SOURCE_REVISION)
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '0'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: quarkus-hello
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:868966ef9d4b54952d8a74eb83bba40eb1f52c0148994fa704efd0e3797c61c5
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: unit-tests
      params:
        - name: GOALS
          value:
            - package
            - '-f'
            - quarkus-hello
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: source
          workspace: workspace
        - name: maven-settings
          workspace: maven-settings
    - name: code-analysis
      params:
        - name: GOALS
          value:
            - install
            - 'sonar:sonar'
            - '-f'
            - quarkus-hello
            - >-
              -Dsonar.host.url=https://sonarqube-cicd.apps.cluster-df6hj.sandbox169.opentlc.com
            - '-Dsonar.userHome=/tmp/sonar'
            - '-Dsonar.login=cf0e316085290b5479467ac53e3f6597da7e95e3'
            - '-DskipTests=true'
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: source
          workspace: workspace
        - name: maven-settings
          workspace: maven-settings
    - name: dependency-report
      taskRef:
        name: dependency-report
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: workspace
        - name: maven-settings
          workspace: maven-settings
      params:
        - name: SOURCE_DIR
          value: quarkus-hello
    - name: release-app
      params:
        - name: GOALS
          value:
            - deploy
            - '-f'
            - quarkus-hello
            - '-DskipTests=true'
            - >-
              -DaltDeploymentRepository=nexus::default::http://nexus-cicd.apps.cluster-df6hj.sandbox169.opentlc.com/repository/mvn-release/
      runAfter:
        - code-analysis
        - unit-tests
        - dependency-report
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: source
          workspace: workspace
        - name: maven-settings
          workspace: maven-settings
    - name: build-image
      taskRef:
        name: s2i-java-21
      runAfter:
        - release-app
      params:
        - name: TLSVERIFY
          value: "false"
        - name: MAVEN_MIRROR_URL
          value: http://nexus-cicd.apps.cluster-df6hj.sandbox169.opentlc.com/repository/maven-public/
        - name: PATH_CONTEXT
          value: quarkus-hello/target
        - name: IMAGE_NAME
          value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/quarkus-hello
        - name: IMAGE_TAG
          value: $(params.APP_IMAGE_TAG)
      workspaces:
        - name: source
          workspace: workspace
    - name: image-scan
      runAfter:
        - build-image
      taskRef:
        name: rox-image-scan
        kind: ClusterTask
      params:
        - name: image
          value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/quarkus-hello:latest
        - name: rox_api_token
          value: roxsecrets
        - name: rox_central_endpoint
          value: roxsecrets
        - name: output_format
          value: table
        - name: image_digest
          value: $(tasks.build-image.results.IMAGE_DIGEST)
    - name: image-check
      runAfter:
        - build-image
      taskRef:
        name: rox-image-check
        kind: ClusterTask
      params:
        - name: image
          value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/quarkus-hello:latest
        - name: rox_api_token
          value: roxsecrets
        - name: rox_central_endpoint
          value: roxsecrets
        - name: image_digest
          value: $(tasks.build-image.results.IMAGE_DIGEST)
    - name: deploy-check
      runAfter:
        - build-image
      taskRef:
        name: rox-deployment-check
        kind: ClusterTask
      params:
        - name: GIT_REPOSITORY
          value: "$(params.APP_MANIFESTS_GIT)"
        - name: rox_api_token
          value: roxsecrets
        - name: rox_central_endpoint
          value: roxsecrets
        - name: file
          value: deployment.yaml
        - name: deployment_files_path
          value: app
      workspaces:
        - name: workspace
          workspace: workspace

    - name: update-deployment
      runAfter:
        - image-scan
        - image-check
        - deploy-check
      taskRef:
        name: git-update-deployment
      params:
        - name: GIT_REPOSITORY
          value: "$(params.APP_MANIFESTS_GIT)"
        - name: GIT_USERNAME
          value: gogs
        - name: GIT_PASSWORD
          value: gogs
        - name: CURRENT_IMAGE
          value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/quarkus-hello:latest
        - name: NEW_IMAGE
          value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/quarkus-hello
        - name: NEW_DIGEST
          value: "$(tasks.build-image.results.IMAGE_DIGEST)"
        - name: KUSTOMIZATION_PATH
          value: environments/dev
  workspaces:
    - name: maven-settings
    - name: workspace
