apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: pipeline-<app-name>-
  namespace: {{ pipeline_name }}
  labels:
    tekton.dev/pipeline: {{ pipeline_name }}
spec:
  params:
    - name: APP_NAME
      value: quarkus-hello
    - name: GIT_REPO
      value: 'http://gogs-gogs.apps.cluster-xbmk6.dynamic.redhatworkshops.io/gogs/quarkus-hello.git'
    - name: GIT_BRANCH
      value: master
    - name: GIT_USER
      value: gogs
    - name: GIT_PASS
      value: gogs
    - name: PATH_CONTEXT
      value: .
    - name: IMAGE_NAME
      value: 'image-registry.openshift-image-registry.svc:5000/dev-quarkus-hello/quarkus-hello'
    - name: IMAGE_TAG
      value: latest
    - name: JAVA_IMAGE
      value: image-registry.openshift-image-registry.svc:5000/openshift/openjdk-21:1.21-3
    - name: APP_MANIFESTS_GIT
      value: 'http://gogs-gogs.apps.cluster-xbmk6.dynamic.redhatworkshops.io/gogs/quarkus-hello-config.git'
  pipelineRef:
    name: generic-pipeline
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - configMap:
        name: cm-maven-settings
      name: maven-settings
    - name: workspace
      persistentVolumeClaim:
        claimName: pvc-workspace
