apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name:  quarkus-hello-pipeline-run
  namespace: "{{ pipeline_namespace }}"
spec:
  pipelineRef:
    name:  "{{ pipeline_namespace }}"
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: pvc-workspace
    - name: maven-settings
      configMap:
        name: maven-settings