kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-workspace
  namespace: quarkus-hello-cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp3-csi
  volumeMode: Filesystem
