apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: coolstore-cicd:triggers.tekton.dev/EventListener:coolstore-cicd/catalog
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"triggers.tekton.dev/v1beta1","kind":"EventListener","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"coolstore-cicd:triggers.tekton.dev/EventListener:coolstore-cicd/catalog"},"name":"catalog","namespace":"coolstore-cicd"},"spec":{"serviceAccountName":"pipeline","triggers":[{"bindings":[{"kind":"TriggerBinding","ref":"coolstore"}],"template":{"ref":"catalog"}}]}}
  creationTimestamp: "2024-12-16T07:28:47Z"
  generation: 1
  name: catalog
  namespace: coolstore-cicd
  resourceVersion: "81899"
  uid: d1452674-7e88-47ea-8850-a2710514f805
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: TriggerBinding
      ref: coolstore
    template:
      ref: catalog
status:
  address:
    url: http://el-catalog.coolstore-cicd.svc.cluster.local:8080
  conditions:
  - lastTransitionTime: "2024-12-16T16:17:40Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-12-16T16:17:40Z"
    message: Deployment exists
    status: "True"
    type: Deployment
  - lastTransitionTime: "2024-12-16T07:29:24Z"
    message: ReplicaSet "el-catalog-5d597dbd8f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-12-16T16:17:40Z"
    message: EventListener is ready
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-12-16T16:17:40Z"
    message: Service exists
    status: "True"
    type: Service
  configuration:
    generatedName: el-catalog
