apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: coolstore-cicd:triggers.tekton.dev/EventListener:coolstore-cicd/quay
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"triggers.tekton.dev/v1beta1","kind":"EventListener","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"coolstore-cicd:triggers.tekton.dev/EventListener:coolstore-cicd/quay"},"name":"quay","namespace":"coolstore-cicd"},"spec":{"serviceAccountName":"pipeline","triggers":[{"bindings":[{"kind":"TriggerBinding","ref":"quay"}],"interceptors":[{"name":"quay-filter-overlay","params":[{"name":"filter","value":"body.updated_tags[0] in ['prod']"}],"ref":{"name":"cel"}}],"name":"quay-webhook","template":{"ref":"quay"}}]}}
  creationTimestamp: "2024-12-16T07:28:47Z"
  generation: 1
  name: quay
  namespace: coolstore-cicd
  resourceVersion: "62823"
  uid: a62a6dce-12cb-4a5e-9ef9-a6bc8d8f2231
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: TriggerBinding
      ref: quay
    interceptors:
    - name: quay-filter-overlay
      params:
      - name: filter
        value: body.updated_tags[0] in ['prod']
      ref:
        kind: ClusterInterceptor
        name: cel
    name: quay-webhook
    template:
      ref: quay
status:
  address:
    url: http://el-quay.coolstore-cicd.svc.cluster.local:8080
  conditions:
  - lastTransitionTime: "2024-12-16T07:29:07Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-12-16T07:29:07Z"
    message: Deployment exists
    status: "True"
    type: Deployment
  - lastTransitionTime: "2024-12-16T07:29:07Z"
    message: ReplicaSet "el-quay-6b6b59fb74" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-12-16T07:29:07Z"
    message: EventListener is ready
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-12-16T07:29:07Z"
    message: Service exists
    status: "True"
    type: Service
  configuration:
    generatedName: el-quay
